name: 'Nest Deploy'
on: 
  push

jobs: 
  nest-deploy:
    name: Nest Deploy
    runs-on: ubuntu-latest
    environment: deploy
    uses: appleboy/ssh-action@v1.0.3
    with: 
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      key: ${{ secrets.KEY }}
      env: 
        deployscript: ${{ secrets.SCRIPT }}
      steps: 
        - name: Connect via SSH and pull changes
          script: |
              cd ${{ secrets.DIRECTORY }}            
              git pull
        - name: Run optional post-pull script
          if: ${{ env.deployscript }}
          run: |
            /usr/bin/bash -l ${{ env.deployscript }}