name: 'ssh-deploy'
on: 
  push

jobs: 
  nest-deploy:
    name: SSH Deploy
    runs-on: ubuntu-latest
    environment: deploy
    steps: 
      - name: Connect via SSH and pull changes
        uses: appleboy/ssh-action@v1.0.3
        env: 
          deployscript: ${{ secrets.SCRIPT }}
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ${{ secrets.DIRECTORY }}            
            git pull
            bun run build